language: node_js
sudo: false
node_js:
  - "4.1"
addons:
  apt:
    sources:
       - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
env:
  - TRAVIS=travis CXX=g++-4.8
notifications:
  email:
    on_success: never
    on_failure: always
